server:
  compression:
     enabled: true
     mime-types: application/json,application/xml,text/html,text/xml,text/plain
  server-header: hub-concur-connector

connector:
  hasTestAuth: true

management:
  endpoints:
    web.base-path: /

# If the tenant belongs to EU region, then we have to change the oauth instance url.
concur:
  oauth-instance-url: https://us-impl.api.concursolutions.com
